"""Initial migration.

Revision ID: 430db8d4679d
Revises: 
Create Date: 2026-01-07 16:57:31.899316

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '430db8d4679d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('species', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pets')
    # ### end Alembic commands ###
